version: "3"
services:
  postgresql:
    image: postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=artifactory
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:6.6.3
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    environment:
      - DB_TYPE=postgresql
      - DB_USER=artifactory
      - DB_PASSWORD=artifactory
    volumes:
      - ./data/artifactory:/var/opt/jfrog/artifactory
    depends_on:
      - postgresql

  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - "443:443"
      - "8080:8080"
      - "80:80"
    depends_on:
      - artifactory
      - postgresql