- name: Install Docker

  hosts: artifactory
  
  become: yes
  become_method: sudo

  tasks:

  - name: Check is artifactory folder exists
    stat:
      path: artifactory
    register: artifactory_home

  - name: Clean up docker-compose
    command: >
       docker-compose down
    args:
       chdir: artifactory/
    when: artifactory_home.stat.exists

  - name: Delete artifactory working-dir
    file:
       state: absent
       path: artifactory
    when: artifactory_home.stat.exists

  - name: Copy artifactory working-dir
    synchronize:
       src: ./artifactory/
       dest: artifactory
  - name: Generate a Self Signed OpenSSL certificate
    command: >
       openssl req -subj '/CN=artifactory-server' -x509 -newkey rsa:4096 -nodes
       -keyout key.pem -out cert.pem -days 999
    args:
       chdir: /vagrant/artifactory-install/artifactory/nginx-config/
  - name: docker pull hello world to initialize docker compose 
    command: > 
       docker pull hello-world
  - name: Call docker-compose to run artifactory

    command: >
       docker-compose -f docker-compose.yml up -d
    args:
       chdir: /home/vagrant/artifactory
